version: '1.0'

services:
  php-app:
    image: php:8.0-apache
    container_name: k8s-misconfig-demo
    ports:
      - "6443:80"
    volumes:
      - ./src:/var/www/html
      - ./apache-custom.conf:/etc/apache2/conf-enabled/custom.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

